name: python tests

on: pull_request

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r API/requirements.txt
      - run: pip install -r AI/requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: /home/runner/work/SystemCiuch/SystemCiuch
        run: |
          pip install pytest pytest-cov requests torch
          python ./API/main.py && sleep 3 && pytest Tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html && kill -9 `lsof -i:8000 -t`
