name: python tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r API/requirements.txt
      - run: pip install -r AI/requirements.txt
      - run: pip install -r Tests/requirements.txt
      - name: Test with pytest
        working-directory: ./Tests
        env:
          PYTHONPATH: /home/runner/work/SystemCiuch/SystemCiuch
        run: |
          python3 run_app.py &
          pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
